### ISSUE TITLE
Not working in latest Firefox

### ISSUE THREAD

**Issue by cfjedimaster** [andyhall/ractive-drag-events#1]
Title says it all. Specifically - the online demo.

**Comment by fenomas** [comment]
Thanks Ray, bug in the example. It seems that Firefox doesn't consider a drag to be happening unless you actually assign some data to the drag event:

`event.dataTransfer.setData('mimetype', 'foo')`

**Comment by cfjedimaster** [comment]
confirmed

**Comment by fenomas** [comment]
confirmation confirmed. :+1:
